version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  gateway_service:
    build: gateway_service
    container_name: gateway_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - library_system
      - rating_system
      - reservation_system

  library_system:
    build: library_system
    container_name: library_system
    restart: always
    ports:
      - "8060:8060"
    depends_on:
      - postgres

  rating_system:
    build: rating_system
    container_name: rating_system
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - postgres

  reservation_system:
    build: reservation_system
    container_name: reservation_system
    restart: always
    ports:
      - "8070:8070"
    depends_on:
      - postgres

volumes:
  db-data: