name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GATEWAY_SERVICE_IMAGE: puzanovim/gateway_service:${{ github.sha }}
  LIBRARY_SYSTEM_IMAGE: puzanovim/library_system:${{ github.sha }}
  RATING_SYSTEM_IMAGE: puzanovim/rating_system:${{ github.sha }}
  RESERVATION_SYSTEM_IMAGE: puzanovim/reservation_system:${{ github.sha }}

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push services
        run: |
          docker build -t ${{ env.GATEWAY_SERVICE_IMAGE }} gateway_service && docker push ${{ env.GATEWAY_SERVICE_IMAGE }}
          docker build -t ${{ env.LIBRARY_SYSTEM_IMAGE }} library_system && docker push ${{ env.LIBRARY_SYSTEM_IMAGE }}
          docker build -t ${{ env.RATING_SYSTEM_IMAGE }} rating_system && docker push ${{ env.RATING_SYSTEM_IMAGE }}
          docker build -t ${{ env.RESERVATION_SYSTEM_IMAGE }} reservation_system && docker push ${{ env.RESERVATION_SYSTEM_IMAGE }}

      - name: Deploy COI VM
        id: deploy-coi
        uses: yc-actions/yc-coi-deploy@v1
        env:
          GATEWAY_SERVICE_IMAGE: ${{ env.GATEWAY_SERVICE_IMAGE }}
          LIBRARY_SYSTEM_IMAGE: ${{ env.LIBRARY_SYSTEM_IMAGE }}
          RATING_SYSTEM_IMAGE: ${{ env.RATING_SYSTEM_IMAGE }}
          RESERVATION_SYSTEM_IMAGE: ${{ env.RESERVATION_SYSTEM_IMAGE }}
          YC_VM_SSH: ${{ secrets.YC_VM_SSH }}
          YC_VM_USERNAME: ${{ secrets.YC_VM_USERNAME }}
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          VM-name: ${{ secrets.YC_VM_NAME }}
          vm-service-account-id: ${{ secrets.YC_SERVICE_ACCOUNT_ID }}
          vm-cores: 1
          vm-memory: 512Mb
          vm-core-fraction: 100
          vm-subnet-id: ${{ secrets.YC_SUBNET_ID }}
          user-data-path: './user-data.yaml'
          docker-compose-path: './docker-compose.yml'

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v4/postman/collection.json
          environment: v4/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"